# Generated by Django 4.2.3 on 2023-07-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_assessment_question_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="title",
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
