# Generated by Django 4.2.3 on 2023-08-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_alter_assessment_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="info",
            field=models.TextField(default="Subject Information Should Be Here"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
