# Generated by Django 4.2.3 on 2023-08-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_subject_info_alter_subject_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="image_link",
            field=models.CharField(
                default="https://i.imgur.com/yI5nb9M.png", max_length=200
            ),
        ),
    ]
