# Generated by Django 4.2.3 on 2023-08-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0009_alter_subject_image_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="intro_video",
            field=models.CharField(
                default="https://www.youtube.com/embed/9nkR2LLPiYo", max_length=400
            ),
        ),
    ]
