# Generated by Django 4.2.3 on 2023-08-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0010_subject_intro_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="video",
            name="url",
            field=models.CharField(max_length=200),
        ),
    ]
