# Generated by Django 4.2.3 on 2023-08-21 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0011_alter_file_file_alter_image_file_alter_video_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="file",
            new_name="image",
        ),
    ]
