# Generated by Django 4.2.3 on 2023-08-21 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0013_alter_content_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="lesson_content",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file",
                to="course.content",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="lesson_content",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="course.content",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="text",
            name="lesson_content",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text",
                to="course.content",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="lesson_content",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to="course.content",
            ),
            preserve_default=False,
        ),
    ]
