# Generated by Django 4.2.3 on 2023-08-21 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0015_content_data_content_text_alter_file_lesson_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="data",
        ),
        migrations.RemoveField(
            model_name="content",
            name="text",
        ),
        migrations.AlterField(
            model_name="file",
            name="lesson_content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.content"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="lesson_content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.content"
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="lesson_content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.content"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="lesson_content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.content"
            ),
        ),
    ]
