# Generated by Django 4.2.3 on 2023-08-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0015_content_data_content_text_alter_file_lesson_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="text",
        ),
        migrations.AlterField(
            model_name="content",
            name="data",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="content",
            name="object_id",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
