# Generated by Django 4.2.3 on 2023-08-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0016_remove_content_text_alter_content_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
    ]
