# Generated by Django 4.2.3 on 2023-07-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_facility",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_mentor",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_student",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Student"),
                    ("mentor", "Mentor"),
                    ("facility", "Facility"),
                ],
                max_length=10,
                verbose_name="Role",
            ),
        ),
    ]
